# Generated by Django 4.1.5 on 2023-01-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Org_Name', models.EmailField(max_length=254)),
                ('Org_Country', models.CharField(max_length=100)),
                ('Org_City', models.CharField(max_length=100)),
                ('Account_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Pswd_Hash', models.CharField(max_length=100)),
                ('Client_Gender', models.CharField(max_length=100)),
                ('Client_Type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
    ]
