# Generated by Django 4.1.5 on 2023-01-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signupform',
            table=None,
        ),
    ]
