# Generated by Django 4.1.5 on 2023-01-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0002_alter_signupform_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUpForm',
            new_name='client_details',
        ),
    ]
