# Generated by Django 4.1.5 on 2023-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0003_rename_signupform_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients_login',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Pswd_Hash', models.CharField(max_length=100)),
                ('Client_Type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clients_login',
            },
        ),
        migrations.AlterField(
            model_name='client_details',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='Org_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='client_details',
            table='client_details',
        ),
    ]
