# Generated by Django 4.1.5 on 2023-01-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0006_admins_alter_clients_pswd_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admins',
        ),
    ]
