# Generated by Django 4.1.5 on 2023-01-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0007_delete_admins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='Pswd_Hash',
            new_name='Password',
        ),
    ]
