# Generated by Django 4.1.5 on 2023-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0008_rename_pswd_hash_clients_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
        migrations.AlterField(
            model_name='client_details',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='Org_Name',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterModelTable(
            name='client_details',
            table=None,
        ),
    ]
