# Generated by Django 4.1.5 on 2023-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0009_delete_clients_alter_client_details_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients_login',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Pswd_Hash', models.CharField(max_length=100)),
                ('Client_Type', models.CharField(max_length=100)),
            ],
        ),
    ]
