# Generated by Django 4.1.7 on 2023-03-26 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Admin_Name', models.CharField(max_length=100)),
                ('Admin_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('msgid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=200)),
                ('sender_id', models.CharField(max_length=50, null=True)),
                ('reciever_id', models.CharField(max_length=50, null=True)),
                ('msg_time', models.DateTimeField()),
                ('reciever_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_chats', to='contenttypes.contenttype')),
                ('sender_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_chats', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
    ]
