# Generated by Django 4.1.7 on 2023-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
