# Generated by Django 4.1.7 on 2023-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Admin_Name', models.CharField(max_length=100)),
                ('Admin_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
