# Generated by Django 4.1.7 on 2023-04-05 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('model_path', models.CharField(default=' ', max_length=255)),
                ('model_for', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('rmse', models.FloatField()),
            ],
            options={
                'db_table': 'trained_models',
            },
        ),
    ]
