# Generated by Django 4.1.7 on 2023-04-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='rmse',
            field=models.FloatField(null=True),
        ),
    ]
