# Generated by Django 4.1.7 on 2023-04-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_trainedmodel_accuracy_alter_trainedmodel_rmse'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='silhouette',
            field=models.FloatField(null=True),
        ),
    ]
