# Generated by Django 4.1.7 on 2023-03-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0004_client_details_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_details',
            table=None,
        ),
    ]
