# Generated by Django 4.1.7 on 2023-03-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0006_alter_client_details_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_details',
            table=None,
        ),
    ]
