# Generated by Django 4.1.7 on 2023-03-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0007_alter_client_details_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client_details',
            table='client_details',
        ),
    ]
