# Generated by Django 4.1.7 on 2023-03-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0008_alter_client_details_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details',
            old_name='username',
            new_name='Username',
        ),
    ]
