# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0009_rename_username_client_details_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_details',
            old_name='Username',
            new_name='username',
        ),
    ]
