# Generated by Django 4.1.7 on 2023-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0011_client_details_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='account_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='client_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='org_city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='org_country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='org_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='username',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
