# Generated by Django 4.1.7 on 2023-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0013_alter_client_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='gender',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
